config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { registrations: 'registrations' }  

  root 'posts#index'  

resources :posts do  
  resources :comments
end  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
		validates :user_id, presence: true 
	  	validates :image, presence: true
		belongs_to :user 
		has_attached_file :image, styles: { :medium => "640x" }
		validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
		has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base

		validates :user_name, presence: true, length: { minimum: 5, maximum: 16 }  
		has_many :posts, dependent: :destroy  
	  # Include default devise modules. Others available are:
	  # :confirmable, :lockable, :timeoutable and :omniauthable
  		devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

	def create  
	  @comment = @post.comments.build(comment_params)
	  @comment.user_id = current_user.id

	  if @comment.save
	    flash[:success] = "Thank you for the comment!"
	    redirect_to :back
	  else
	    flash[:alert] = "Check the comment form, something went horribly wrong."
	    render root_path
	  end
	end
		def destroy  
		  @comment = @post.comments.find(params[:id])

		  @comment.destroy
		  flash[:success] = "Comment deleted :("
		  redirect_to :back
		end  
	private

	def comment_params  
	  params.require(:comment).permit(:content)
	end

	def set_post  
	  @post = Post.find(params[:post_id])
	end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user! 
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :owned_post, only: [:edit, :update, :destroy]
	def index
		#Let’s call our instance variable @posts. All we then want to do is capture all of the posts in the Post model!
		@posts = Post.all
	end
	def show  
  		#@post = Post.find(params[:id])

	end  

	def new
	    @post = current_user.posts.build
	  end

	  def create
	    @post = current_user.posts.build(post_params)

	    if @post.save
	      flash[:success] = "Your post has been created!"
	      redirect_to posts_path
	    else
	      flash[:alert] = "Your new post couldn't be created!  Please check the form."
	      render :new
	    end
	  end  
	def edit  
		#@post = Post.find(params[:id])
	end

	def update  
		if @post.update(post_params)
		  flash[:success] = "Post updated."	
		  #@post.update(post_params)
		  redirect_to posts_path
	  else
	  	flash.now[:alert] = "Update failed.  Please check the form."
		render :edit
	  end
	end  
	def destroy
		#@post = Post.find(params[:id])
		if @post.destroy
			flash[:notice] = "Your posted image was destroyed and will never be accessible again"  
			redirect_to root_path
		else
			flash.now[:alert] = "Destroy failed.  Check if the image exist or refresh the page and try again."
		end
	end

	private
	def post_params  
	  	params.require(:post).permit(:image, :caption)
	end  
	def set_post
		@post = Post.find(params[:id]) 
	end
	def owned_post  
  unless current_user == @post.user
    flash[:alert] = "Nice play ! but that post dosn't belong to you."
    redirect_to root_path
  end
end  

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_for(flash_type)  
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
end  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
        
<nav class="navbar navbar-inverse ">
    
    <div class="navbar-header ">
      <a class="navbar-brand" href="/"><img alt="logo" src="/">Photobook</a>
    </div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if user_signed_in? %>
      <p class="navbar-text navbar-left">Signed in as <a href="#" class="navbar-link"><%= current_user.user_name %></a></p>
        <% else %> 
      <p class="navbar-text navbar-left">Your are not logged in, please login or register to post </p>
        <% end %>
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">

        </div>
        <button type="submit" class="btn btn-default">Submit</button>
        
      </form>
      <% if user_signed_in? %>
        <%= render 'layouts/showprofil'%>
        <% else %> 
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= new_user_session_path %>">Login</a></li>
        <li><a href="<%= new_user_registration_path %>">Register</a></li>
      </ul>        
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_showprofil.html.erb
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My profil<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= new_post_path%>">Add post</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Edit post" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Edit Profil", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "style" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
</div>  
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="container">
<%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
<%= f.input :image, label: "Choose your image: No files exept images are allowed", class: "form-group" %>
<%= f.input :caption, placeholder: 'Describe your image', class: " form-group text-center" %>
<%= f.button :submit, class: 'btn-success' %>
<% end %>
</div>

app/views/posts/_post.html.erb
<h3>Comments:</h3>
<hr>
  <% if @post.comments %>
    <% @post.comments.each do |comment| %>
        <div id="comment">
            <div class="user-name">
              <%= comment.user.user_name %> :
            </div>
            <div class="comment-content">
              <%= comment.content %>
            </div>
            <% if comment.user == current_user %>
              <%= link_to "Delete", post_comment_path(@post, comment),class: "glyphicon glyphicon-remove delete-comment", method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
        
        <hr>
    <% end %>
  <% end %>
        <div class="comment-like-form row">
          <div class="comment-form col-sm-11">
              <%= form_for [@post, @post.comments.new] do |f| %>
                <%= f.text_area :content, placeholder: 'Add a comment...', autofocus: true, class: "form-control" %>
                <%= f.submit class: 'btn btn-success'  %>
              <% end %>  
          </div> 
        </div>
        </div>
  </br>

app/views/posts/edit.html.erb
<div class='text-center'><h1>Edit <%= @post.caption %></h1></div>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>PhotoBook</h1>
  <div class="container">
<% @posts.each do |post| %>
  <div class="row-image">
  <div class="col-xs-6 col-md-3">
    <a href="<%= post_path(post) %>" class="thumbnail">
      <img src="<%= post.image.url(:medium) %>" alt="<%= post.caption %>">
    </a>
      <div class="caption">
  <p><%= post.caption %></p>
  </div>
  </div>
</div>
<% end %>
</div>

  <!-- page pagination -->
<nav aria-label="Page navigation">
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

app/views/posts/new.html.erb
<div class='text-center'><h1>Add post</h1></div>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class='posts-wrapper row'>
  <div class='post'>
    <div class='image center-block'>
      <%=link_to (image_tag @post.image.url(:medium), class:'img-responsive'), posts_path%>
    </div>
    <div class="post-bottom">
      <p class='caption'><a>About image:</a> <%= @post.caption %></p>
      <p class="post-head">Added by <%= @post.user.user_name unless @post.user.blank?%></p>
     
    </div>
    <div class='text-center right'>
   <%= link_to "Cancel", posts_path, class: 'btn btn-success' %>
   <% if @post.user.id == current_user.id %>
   |
  <%= link_to "Edit Post", edit_post_path(@post), class: 'btn btn-primary' %>
  |
  <%= link_to "Delete Post", post_path(@post), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure you want to delete this Photo?", disable_with: 'loading...' } %>
  <% else %>
  <% end %>
    </div>


  </div>
 <!-- Comment -->
<%= render 'post' %>
<!-- End comment -->

</div>